version: "3.8"

services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    container_name: ${SERVER_NAME}
    environment:
      EULA: "true"
      MAX_MEMORY: 2G
      VIEW_DISTANCE: 15
      MAX_PLAYERS: 4
    ports:
      - "25565:25565"
    volumes:
      - ${FOLDER}:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}