version: "3.8"
services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    container_name: ${NAME:-delMe}
    environment:
      MOTD: ${MOTD:-"Welcome to delme"}
      EULA: "true"
      OPS: ${OPS:-itomten}
      MAX_MEMORY: ${MEM:-2G}
      VIEW_DISTANCE: ${VIEW:-15}
      MAX_PLAYERS: ${PLAYERS:-3}
      VERSION: ${VERSION:-LATEST}
      TYPE: ${TYPE:-VANILLA}
      MODE: ${GAMDEMODE:-SURVIVAL}
      RCON_PASSWORD: ${RCON_PASSWORD:-minecraft}
    ports:
      - "${PORT:-25565}:25565"
      - "${RCON:-25575}:25575"
    volumes:
      - /mnt/nasworld/${RACK:-dev}/${NAME:-delMe}:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}