
services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - /mnt/nasworld/singelMc1:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}