version: "3.8"

services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    environment:
    EULA: "true"
    MAX_MEMORY: 2G
    VIEW_DISTANCE: 15
    MAX_PLAYERS: 4
    ports:
      - "25565:25565"
    volumes:
      - /mnt/nasworld/singelMc1:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}